version: "3"

 

services:

  app:
    # image: latamtest
    build: /.
    container_name: latamtest
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    # command: ["python","api.py"]